[package]
name = "nexure/react-animation"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

React = "core-packages/react@17.0.1-rc.18"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"
Promise = "evaera/promise@4.0.0"

